services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000   # use backend service name instead of localhost
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_c
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=${MONGODB_URI}   # Atlas connection string from .env
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    